---
name: "Auto build dev release"

on:
  push:
    branches:
      - "dev"

jobs:
  pre-release:
    name: "Dev Pre-Release - Autobuild"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Install dependencies"
        run: |
            npm install
            npm install -g typescript
            
      - name: "Build"
        run: |
          npm run build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Dev Pre-Release - Autobuild"
          files: |
            build/*