---
name: "Code Checks"

on:
 pull_request:
  types: ["opened", "edited", "reopened", "synchronize", "ready_for_review", "review_requested"]
 push:
  branches:
   - "dev"

jobs:
 ESM:
  name: "Compile & Sanity Check ESM"
  runs-on: "ubuntu-latest"

  steps:
   - uses: actions/checkout@v2
   - name: "Install dependencies"
     run: |
      npm install

   - name: "Compile & Sanity Test"
     run: |
      npm run testESM

 Binary:
  name: "Build & Sanity Check Linux Binary"
  runs-on: "ubuntu-latest"

  steps:
   - uses: actions/checkout@v2
   - name: "Install dependencies"
     run: |
      npm install

   - name: "Build & Sanity Test"
     run: |
      npm run testBinaryLinux

 eslint:
  name: eslint
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: reviewdog/action-eslint@v1
     with:
      reporter: github-check
      eslint_flags: "src/"
      github_token: ${{ secrets.GITHUB_TOKEN }}
